version: "3.9"

services:
  server:
    image: node:20-alpine
    container_name: area_mock_server
    working_dir: /app
    command: >
      sh -c "npx serve . -l 8080"
    ports:
      - "8080:8080"
    volumes:
      - ./about.json:/app/about.json
    restart: unless-stopped

  client_mobile:
    build: ./mobile
    container_name: area_mobile
    volumes:
      - shared-bundle:/shared
    ports:
      - "19000:19000"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEV_SERVER_ORIGIN=http://localhost:19000
    stdin_open: true
    tty: true
    restart: unless-stopped

  client_web:
    build: ./frontend
    container_name: area_web
    working_dir: /app
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - shared-bundle:/shared
    # command: >
    #   sh -c "npm install -g serve &&
    #          echo 'Starting web server...' &&
    #          npx serve /shared -l 8081"
    restart: unless-stopped

volumes:
  shared-bundle:
