services:
  server:
    image: node:20-alpine
    container_name: area_mock_server
    working_dir: /app
    command: >
      sh -c "npx serve . -l 8080"
    ports:
      - "8080:8080"
    volumes:
      - ./about.json:/app/about.json
    restart: unless-stopped

  client_mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile.build
    container_name: area_mobile
    volumes:
      - shared-bundle:/shared
    environment:
      - EXPO_TOKEN=32byPGz6WVXbT2bDtjXlFx1oNWIfIaJIGNb1ItwY
      - EAS_NO_VCS=1
      - EAS_LOCAL_BUILD_SKIP_CLEANUP=1
    restart: "no"

  mobile_dev:
    build: ./mobile
    container_name: area_mobile_dev
    volumes:
      - shared-bundle:/shared
    ports:
      - "19000:19000"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEV_SERVER_ORIGIN=http://localhost:19000
    stdin_open: true
    tty: true
    restart: unless-stopped

  client_web:
    build: ./frontend
    container_name: area_web
    working_dir: /app
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - shared-bundle:/shared
    command: >
      sh -c "npm install -g serve &&
           serve /shared -l 8081"
    restart: unless-stopped

volumes:
  shared-bundle:
