services:
  db:
    image: mariadb:11.8.3
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: area
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: area
    depends_on:
      - db
    volumes:
      - shared-bundle:/shared

  mobile:
    build: ./mobile
    volumes:
      - shared-bundle:/shared

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
      - mobile
    volumes:
      - shared-bundle:/shared

volumes:
  db_data:
  shared-bundle:
